### PR TITLE
fetches new URLs now

### PR DESCRIPTION
**Pull request by stevenhalverson**
compares the current URLs in the html to stored URLs in a .json file. maybe that can be replaced with the database file?

### CODE REVIEW

**Comment by eddyizm** [comment]
Let's change the naming on these files you are working on, instead of test use something like WIP for work in progress. Normally test is a prefix for test files, eg, running tests with pytest, which we can start on soon.

**Comment by stevenhalverson** [comment]
Renamed the files and created new pull request.

**Comment by eddyizm** [comment]
FYI, you can rename and make changes to the same PR.

**Comment by stevenhalverson** [comment]
Ah gotcha. I should probably do that next time. Will try it out.

**Pull request closed without merging**
